[env:esp32-s3-devkitc]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB

monitor_speed = 115200
monitor_port = COM9
upload_port = COM9
upload_protocol = esptool
build_unflags = 
    -std=gnu++11
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -std=gnu++17
    -Wall
    -DBOARD_HAS_PSRAM
board_build.partitions = huge_app.csv
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    mathieucarbou/ESP Async WebServer
    mathieucarbou/AsyncTCP
    bblanchon/ArduinoJson
    madhephaestus/ESP32Encoder
    adafruit/Adafruit NeoPixel